# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
  pull_request:

jobs:
  xcodebuild-16:
    name: Build with xcodebuild on Xcode 16.1
    runs-on: macos-14
    strategy:
      matrix:
        platforms: [
          'generic/platform=ios',
          'generic/platform=tvos',
          'generic/platform=watchos',
          'generic/platform=visionos'
        ]
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_16.1.app/Contents/Developer
      - name: Build Framework
        run: xcrun xcodebuild build -scheme ImperativeNavigation -destination ${{ matrix.platforms }}

  example-package-integration-16:
    name: Build Package Integration on Xcode 16.1
    runs-on: macos-14
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_16.1.app/Contents/Developer
      - name: Build Package Integration
        run: xcrun swift build --package-path Example/ImperativeNavigationExample --destination generic/platform=ios